version: "3"
services:
  service:
    build: app
    expose:
      - "5000"
    env_file:
      - .env
    entrypoint: "uwsgi --strict --ini uwsgi.ini"
    volumes:
      - ${PWD}/csv:/opt/test_web_app/csv/:rw
    
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    depends_on:
      - service

